Edge api
JohanTorfs/instrument_edge_api pull request #66
Opened 2022-10-22 20:28 UTC by Dzetacq

Edge API created with models, controllers. 
NOTE: not yet on (I think) dockerhub, where the okteto deploy looks for it?

2022-10-22 20:31 UTC, Dzetacq commented
wow, sonarcloud really be spamming here

2022-10-23 10:59 UTC, JohanTorfs requested changes
Ziet er heel goed uit, heb een paar opmerkingen en een kleine aanpassing voor de dockerfile. Eens dat dit klaar is, zal ik alles eerst eens lokaal proberen testen.

2022-10-23 10:59 UTC, JohanTorfs commented on .github/workflows/all_docker_deploy.yml
> +        api-name: [instrument_api, piece_api, review_api, edge_api]
This should work.

2022-10-23 10:59 UTC, JohanTorfs commented on edge_api/Dockerfile
> +ENTRYPOINT ["java","-jar","/app.jar"]
You need to add the environment variables (from the application properties file) here. This is needed so the container can find the other containers in the kubernetes cluster

2022-10-23 10:59 UTC, JohanTorfs commented on edge_api/pom.xml
> +        <java.version>17</java.version>
Add the sonarcloud properties. Although they will mostly be overwritten by the input from the workflows. (Look at the other microservices)

2022-10-23 10:59 UTC, JohanTorfs commented on edge_api/pom.xml
> +                <groupId>org.springframework.boot</groupId>
There is an other plugin that needs to be added for sonarcloud to do the coverage checks. Forgot the name of the plugin, but you can find it in the other microservice files

2022-10-23 10:59 UTC, JohanTorfs commented on edge_api/src/main/java/com/example/edge_api/controller/InstrumentController.java
> +    public Instrument getInstrumentWithMusiciansAndPieces(@PathVariable String name) {
Does this not need to return a list? It just seems more logical that it would return a list of instruments that match the given string.

2022-10-23 10:59 UTC, JohanTorfs commented on edge_api/src/main/java/com/example/edge_api/controller/MusicianController.java
> +    public Musician getMusicianWithInstrument(@PathVariable String name) {
Same here. Is a list not more usable?

2022-10-23 10:59 UTC, JohanTorfs commented on edge_api/src/main/resources/application.properties
> +instrumentservice.baseurl= ${INSTRUMENT_SERVICE_BASEURL:localhost:8051}
Ik denk dat de ports niet gaan werken op okteto, dus hier zou je best ook een env variabele toevoegen. Dit moeten we misschien eerst even in een lokale cluster testen.

2022-10-23 10:59 UTC, JohanTorfs commented on okteto-compose.yml
> +        REVIEW_SERVICE_BASEURL: review-service:8053
Waarschijnlijk goed als we deze environment variabelen ook in de dockerfile zetten. De push naar docker en okteto gebeurd trouwens enkel op push naar main.

2022-10-23 11:00 UTC, JohanTorfs commented on okteto-compose.yml
> +        REVIEW_SERVICE_BASEURL: review-service:8053
Ik denk trouwens ook dat de ports hier wegmogen

2022-10-25 18:39 UTC, JohanTorfs commented on edge_api/src/main/java/com/example/edge_api/controller/InstrumentController.java
> +    public Instrument getInstrumentWithMusiciansAndPieces(@PathVariable String name) {
Uitstellen tot front end

2022-10-25 18:39 UTC, JohanTorfs commented on edge_api/src/main/java/com/example/edge_api/controller/MusicianController.java
> +    public Musician getMusicianWithInstrument(@PathVariable String name) {
Front end

2022-10-27 16:28 UTC, merged